Repository Luson045/medi-connect, pull requests merged in 2024-10, with the labels that each got.

#19 update readme and contribution
  CONTRIBUTING.md
  README.md
  client/src/styles/Home.css
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level 2, hacktoberfest, gssoc24-ext

#43 Add feature: New Scroll Bar added. Completed the assign issue #34 done.
  client/src/styles/Home.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level 1, hacktoberfest, gssoc24-ext

#48 Styled the User Profile Page
  README.md
  client/package-lock.json
  client/src/modules/OPD/HospitalList.jsx
  client/src/modules/OPD/HospitalPanal.jsx
  client/src/modules/OPD/Registration.jsx
  client/src/modules/common/AuthForm.jsx
  client/src/modules/common/Profile.jsx
  client/src/modules/common/userContext.jsx
  client/src/styles/UserProfile.css
  server/index.js
Labels: enhancement, hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level 2, hacktoberfest, frontend, gssoc24-ext

#61 Feature Request: Add Zod Validation to API Endpoints #39
  client/package-lock.json
  server/.gitignore
  server/index.js
  server/modules/dashboard/authRoute.js
  server/modules/hospital/index.js
  server/modules/user/index.js
  server/package-lock.json
  server/package.json
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, database, gssoc-ext, level 3, hacktoberfest, gssoc24-ext, auth

#63 Update emergency route to find the nearest hospital and return appointment details
  node_modules/.package-lock.json
  package-lock.json
  package.json
  server/.env.example
  server/.gitignore
  server/index.js
  server/models/hospital.js
  server/modules/dashboard/authRoute.js
  server/modules/hospital/index.js
  server/modules/user/index.js
  server/package-lock.json
  server/package.json
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, backend, database, gssoc-ext, level 3, hacktoberfest, gssoc24-ext

#65 Made the userprofile page responsive
  client/src/modules/common/Profile.jsx
  client/src/styles/UserProfile.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level 2, hacktoberfest, gssoc24-ext

#64 Add feature: What our patients say UI changes. Completed #45 which is assigned.
  client/package-lock.json
  client/package.json
  client/src/assets/profile.jpg
  client/src/assets/profile2.jpg
  client/src/index.css
  client/src/modules/OPD/Home.jsx
  client/src/modules/OPD/PeopleView.jsx
  client/src/modules/OPD/Review.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level 2, hacktoberfest, gssoc24-ext, clean

#69 Email will be sent after booking an appointment
  client/package-lock.json
  client/src/modules/OPD/Registration.jsx
  server/.env.example
  server/index.js
  server/modules/hospital/index.js
  server/modules/mail/sendMail.js
  server/package-lock.json
Labels: bug, hacktoberfest-accepted, gssoc, gssoc-extd, backend, gssoc-ext, level 3, hacktoberfest, gssoc24-ext

#72 people review section working properly : working properly What Our Patients Say section
  client/src/modules/OPD/Review.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level 2, hacktoberfest, gssoc24-ext

#77 Update a field email and fix the registration form
  .env.example
  .gitignore
  client/package-lock.json
  client/src/modules/OPD/Registration.jsx
  server/index.js
Labels: bug, hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#81 SMS Notification for booking confirmation
  server/.env.example
  server/index.js
  server/modules/hospital/index.js
  server/modules/notifications/sendMail.js
  server/modules/notifications/sendSMS.js
  server/package-lock.json
  server/package.json
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#84 Changed emergency route to be independent of authentication
  server/index.js
  server/modules/hospital/index.js
Labels: enhancement, hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#75 Desgin/login page
  client/src/modules/common/AuthForm.jsx
  client/src/styles/Login.css
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#86 Register link issue fix
  client/src/modules/common/AuthForm.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#89 #32 Added Images and made it responsive
  client/src/modules/OPD/Home.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#97 added footer
  client/src/App.js
  client/src/assets/facebook-brands-solid.svg
  client/src/assets/instagram-brands-solid.svg
  client/src/assets/linkedin-brands-solid.svg
  client/src/assets/x-twitter-brands-solid.svg
  client/src/modules/common/Footer.jsx
  client/src/styles/Footer.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#88 Form validated with proper error messages
  client/src/modules/common/AuthForm.jsx
  client/src/styles/Login.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#90 Upstyled the review cards
  client/package-lock.json
  client/package.json
  client/src/modules/OPD/Review.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#107 Add Automated Greeting Workflow for New Contributors
  .github/workflows/greetings.yml
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#113 Feature/passwordshowhide : Done Password toggle button added for show and hide password #93 done
  client/src/modules/common/AuthForm.jsx
  client/src/styles/Login.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#115 Changes made on Add greetings configurations
  .github/workflows/greetings.yml
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#96 Update registration form for emergency route
  .env.example
  client/src/modules/OPD/Registration.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#108 Added DockerFile | Updated Readme.md
  README.md
  client/Dockerfile
  docker-compose.yaml
  server/Dockerfile
  server/index.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#124 Fixes #104 | Configure prettier for code consistency.
  README.md
  client/.prettierignore
  client/.prettierrc
  client/package-lock.json
  client/package.json
  server/.prettierignore
  server/.prettierrc
  server/package-lock.json
  server/package.json
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#131 Footer Updated issue Resolved #102
  client/src/styles/Footer.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#135 added "scrollToTop" functionality.
  client/src/modules/common/Footer.jsx
  client/src/styles/Footer.css
Labels: hacktoberfest-accepted, hacktoberfest

#152 fixed the design of login and register button #120
  client/src/styles/Login.css
Labels: good first issue, hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#150 Feature/navbar UI
  client/.prettierrc
  client/postcss.config.js
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/modules/OPD/Chart.jsx
  client/src/modules/OPD/HospitalList.jsx
  client/src/modules/OPD/HospitalPanal.jsx
  client/src/modules/OPD/Registration.jsx
  client/src/modules/OPD/Review.jsx
  client/src/modules/OPD/Success.jsx
  client/src/modules/common/About.jsx
  client/src/modules/common/AuthForm.jsx
  client/src/modules/common/Navbar.jsx
  client/src/modules/common/Profile.jsx
  client/src/modules/common/notification.jsx
  client/src/modules/common/userContext.jsx
  client/src/reportWebVitals.js
  client/src/styles/Home.css
  client/src/styles/HospitalList.css
  client/src/styles/HospitalPanal.css
  client/src/styles/Login.css
  client/src/styles/Navbar.css
  client/src/styles/OPD.css
  client/src/styles/UserProfile.css
  client/tailwind.config.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#151 Improved Landing Page and Research and Data Section
  client/package-lock.json
  client/package.json
  client/src/modules/OPD/Home.jsx
  client/src/modules/OPD/PatientDistributionChart.jsx
  client/src/modules/OPD/TableComponent.jsx
  client/src/modules/common/FloatingIcons.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#160 Fixed Scroll Bar & Changed Color to Blue
  client/src/modules/OPD/Home.jsx
  client/src/styles/Home.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#167 feat:#110 Added a Service page
  client/src/App.js
  client/src/data/index.js
  client/src/modules/OPD/Home.jsx
  client/src/modules/common/Service.jsx
  client/src/styles/Home.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#157 Icons Added in Footer #149
  client/package-lock.json
  client/src/assets/blood-test.gif
  client/src/assets/business.gif
  client/src/assets/call-center.gif
  client/src/assets/consultation.gif
  client/src/assets/doctors-office.gif
  client/src/assets/health-checkup.gif
  client/src/assets/hospital.gif
  client/src/assets/join.gif
  client/src/assets/price-tag.gif
  client/src/assets/support.png
  client/src/assets/terms-and-conditions.png
  client/src/modules/common/Footer.jsx
  client/src/styles/Footer.css
  server/.env.example
Labels: hacktoberfest-accepted, hacktoberfest

#174 Enhanced OPD Form with Report Upload and UX Improvements
  client/src/modules/OPD/Registration.jsx
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#173 redesign logo and favicon
  client/public/1.png
  client/public/3.png
  client/public/favicon.png
  client/public/index.html
  client/public/logo.png
  client/src/modules/common/Navbar.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#161 chore: Add a /assign to automatically assign the issue
  .github/workflows/repo-management.yml
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#178 Update Footer.jsx
  client/src/modules/common/Footer.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#183 updated navbar for android use and added vercel analytics
  client/package-lock.json
  client/package.json
  client/src/index.js
  client/src/modules/common/Footer.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#177 improve the navbar and its responsiveness
  client/package-lock.json
  client/src/modules/common/About.jsx
  client/src/modules/common/Navbar.jsx
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#184 pincode error message solved
  .gitignore
  client/package-lock.json
  client/src/modules/common/AuthForm.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#172 Use pincode validator to check for valid pincodes
  client/package-lock.json
  client/package.json
  client/src/modules/OPD/Registration.jsx
  client/src/modules/common/AuthForm.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#192 Additon of All Contributors | Issue #186
  README.md
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#190 Instant OPD card and redirecting to user profile on confirmation of appointment
  client/package-lock.json
  client/package.json
  client/src/modules/OPD/HospitalList.jsx
  client/src/modules/OPD/Registration.jsx
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#196 Address validation fixed in Instant OPD form
  client/src/modules/OPD/Registration.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#198 Review Card Fixed
  client/src/modules/OPD/Review.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#204 Change open graph image & quality
  client/public/index.html
  client/public/og-medspace-1200x630.png
  client/public/og-medspace-wp.png
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#202 Improve Cursor Effect for Enhanced User Experience.
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/modules/OPD/Home.jsx
  client/src/modules/common/AnimatedCursor.jsx
  client/src/modules/common/Loader.jsx
  client/src/styles/AnimatedCursor.css
  client/src/styles/Home.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#206 Fix Appointment Deletion Across Hospital and User Documents
  server/modules/hospital/index.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext, auth

#209 Implement Loader Page for Improved User Experience
  client/src/modules/OPD/Home.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#218 Fix: Layout Issues
  client/package-lock.json
  client/src/index.js
  client/src/modules/OPD/HospitalList.jsx
  client/src/modules/common/About.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#222 Designed hospital cards using tailwind css issue no @Luson045#44.
  client/package-lock.json
  client/src/modules/OPD/HospitalList.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#249 Feature/aboutuspage about us page redesign #211 done
  client/package-lock.json
  client/package.json
  client/src/assets/images/luson.jpg
  client/src/modules/common/About.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#257 Added header and footer in modal issue #217
  client/package-lock.json
  client/src/modules/OPD/Registration.jsx
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#260 Updated to remove the read more phrase
  client/src/modules/common/Service.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#285 Integrate Grafana and Prometheus Monitoring and Update README Setup Guide
  server/.env.example
  server/.gitignore
  server/README.md
  server/docker-compose.yml
  server/index.js
  server/modules/dashboard/authRoute.js
  server/modules/hospital/index.js
  server/package-lock.json
  server/package.json
  server/prometheus-config.yml
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#271 [FIX] Bug, Feature and Pull Request Preset Added
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#286 loader added on login and instant OPD
  client/src/modules/OPD/Registration.jsx
  client/src/modules/common/AuthForm.jsx
  client/src/styles/Loader.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#298 add: scrolltotop feat while navigation
  client/package-lock.json
  client/src/App.js
  client/src/modules/comps/ScrollToTop.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#303 Changed the padding for mobile view.
  client/src/styles/UserProfile.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#312 Changed the Readme.md File for the Demo link
  README.md
Labels: good first issue, hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#308 Issue #265: [FEATURE] Add Lab Test page solved
  client/src/App.js
  client/src/assets/Hemoglobin.png
  client/src/assets/bloodglucose.png
  client/src/assets/cbc.png
  client/src/assets/ecg.png
  client/src/assets/hepatitis-B.png
  client/src/assets/lipid-profile.png
  client/src/assets/potassium.png
  client/src/assets/ra.png
  client/src/assets/sodium.png
  client/src/assets/thyroid.png
  client/src/assets/urinetest.png
  client/src/assets/usg.png
  client/src/modules/LabTest/LabTest.jsx
  client/src/modules/common/Navbar.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#305 🔒 Enhance password validation with stronger security rules
  client/src/modules/Registration/StepOne.jsx
  server/modules/dashboard/authRoute.js
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#318 Add Multilingual Translator to MediConnect Application
  client/public/google.png
  client/src/modules/common/Footer.jsx
  client/src/modules/common/GoogleTranslate.jsx
Labels: enhancement, hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#324 Added blog pages
  client/public/images/d1.jpg
  client/public/images/d2.jpg
  client/public/images/d3.jpg
  client/src/App.js
  client/src/data/blog-posts.js
  client/src/modules/common/Blog.jsx
  client/src/modules/common/BlogDetailsPage.jsx
  client/src/modules/common/Navbar.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#313 Refactor: Introduce Utils Directory for Enhanced Code Organization
  .env.example
  .gitignore
  client/.gitignore
  node_modules/.package-lock.json
  package-lock.json
  package.json
  server/.gitignore
  server/index.js
  server/utils/cors/corsConfig.js
  server/utils/db/connectDB.js
  server/utils/index.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#319 Feat/dark mode toggle
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.js
  client/src/modules/OPD/Home.jsx
  client/src/modules/common/Navbar.jsx
  client/src/store/atom.js
  client/src/styles/AnimatedCursor.css
  client/src/styles/Home.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest

#322 Feat: Added pre-commit hook for ESLint and prettier
  .gitignore
  .husky/pre-commit
  CONTRIBUTING.md
  eslint.config.mjs
  package-lock.json
  package.json
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#341 Terms and Condition Page
  client/src/App.js
  client/src/modules/common/Footer.jsx
  client/src/modules/common/TermsAndConditions.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#353 Chore : fixed zod schema for dob
  server/modules/dashboard/authRoute.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#340 added hospitals-around in updated code-issue 228
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/modules/common/HospitalsAround.jsx
  client/src/modules/common/Navbar.jsx
Labels: gssoc, gssoc-extd, gssoc-ext, level3, gssoc24-ext

#347 Update gitignore
  .gitignore
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#357 Added Filter in hospital search bar
  client/src/data/hospitalsData.js
  client/src/modules/OPD/HospitalList.jsx
  server/seeds/hospitalSeeder.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#356 Bug Fixed: Ensured Dark/Light Toggle Reflects Changes on About, OPD, …
  client/src/modules/LabTest/LabTest.jsx
  client/src/modules/OPD/Registration.jsx
  client/src/modules/common/About.jsx
  client/src/modules/common/Blog.jsx
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#367 Issue #317 Fixed the footer from scratch
  client/src/modules/common/Footer.jsx
  client/src/modules/common/GoogleTranslate.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#377 [Feat] Redesign Form Layout in registerOPD Page for Better Usability, Visual Appeal, and Responsiveness
  client/src/modules/OPD/Registration.jsx
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest

#376 bugfix/reload-on-btnClick
  client/src/modules/Registration/StepOne.jsx
Labels: good first issue, hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest, gssoc24-ext

#368 Refactor: Organize Backend Code for Better Structure and Maintainability
  server/config/geocoder.js
  server/controllers/auth/authController.js
  server/controllers/user/profileController.js
  server/index.js
  server/middlewares/authMiddleware.js
  server/models/hospital.js
  server/modules/dashboard/authRoute.js
  server/routes/auth/auth.js
  server/routes/user/profile.js
  server/utils/bcrypt/bcryptUtils.js
  server/utils/index.js
  server/validators/authSchemas.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#343 Details Regarding Labtest is added
  client/package-lock.json
  client/src/modules/LabTest/LabTest.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#369 Bug Fixed: Resolve dark/light theme inconsistencies on Register and L…
  client/src/modules/Registration/MultiStepRegistration.jsx
  client/src/modules/Registration/Registration.jsx
  client/src/modules/Registration/ReviewDetails.jsx
  client/src/modules/Registration/StepOne.jsx
  client/src/modules/Registration/StepTwo.jsx
  client/src/modules/common/AuthForm.jsx
  client/src/styles/Login.css
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#391 Fixes : setBasicDetails-undefined
  client/package-lock.json
  client/package.json
  client/src/modules/Registration/StepOne.jsx
  client/src/modules/Registration/StepTwo.jsx
  client/src/modules/common/Medical-Chatbot/Chatbot.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest

#382 Edit User Profile
  client/src/modules/common/Profile.jsx
  client/src/styles/UserProfile.css
  server/controllers/user/profileController.js
  server/routes/user/profile.js
Labels: hacktoberfest-accepted, gssoc, gssoc-ext, level2, hacktoberfest

#403 Modified README.md file
  README.md
Labels: hacktoberfest-accepted, gssoc, gssoc-ext, level1, hacktoberfest

#401 fixed/folder-structure
  client/src/App.js
  client/src/Medical-Chatbot/.gitignore
  client/src/Medical-Chatbot/Chatbot.jsx
  client/src/Medical-Chatbot/index.html
  client/src/Medical-Chatbot/prediction/chat.py
  client/src/Medical-Chatbot/prediction/intents.py
  client/src/Medical-Chatbot/prediction/main.py
  client/src/Medical-Chatbot/prediction/requirements.txt
  client/src/Medical-Chatbot/script.js
  client/src/Medical-Chatbot/style.css
  client/src/Medical-Chatbot/training-chatbot/intents.json
  client/src/Medical-Chatbot/training-chatbot/train_chatbot.py
  client/src/components/AnimatedCursor.jsx
  client/src/components/Cards.jsx
  client/src/components/Chart.jsx
  client/src/components/FloatingIcons.jsx
  client/src/components/Footer.jsx
  client/src/components/GoogleTranslate.jsx
  client/src/components/Layout.jsx
  client/src/components/Loader.jsx
  client/src/components/MultiStepRegistration.jsx
  client/src/components/Navbar.jsx
  client/src/components/PatientDistributionChart.jsx
  client/src/components/Review.jsx
  client/src/components/ReviewDetails.jsx
  client/src/components/ScrollProgressIndicator.jsx
  client/src/components/ScrollToTop.js
  client/src/components/Sidebar.jsx
  client/src/components/StepOne.jsx
  client/src/components/StepTwo.jsx
  client/src/components/TableComponent.jsx
  client/src/components/notification.jsx
  client/src/index.js
  client/src/modules/OPD/NotFound.jsx
  client/src/modules/common/Medical-Chatbot/config.json
  client/src/pages/About.jsx
  client/src/pages/AuthForm.jsx
  client/src/pages/Blog.jsx
  client/src/pages/BlogDetailsPage.jsx
  client/src/pages/Home.jsx
  client/src/pages/HospitalList.jsx
  client/src/pages/HospitalPanal.jsx
  client/src/pages/HospitalsAround.jsx
  client/src/pages/LabTest.jsx
  client/src/pages/NotFound.jsx
  client/src/pages/OPDRegistration.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Registration.jsx
  client/src/pages/Service.jsx
  client/src/pages/Success.jsx
  client/src/pages/TermsAndConditions.jsx
  client/src/store/RegistrationContext.jsx
  client/src/store/userContext.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-ext, level2, hacktoberfest

#420 Create a business contact form in contact us section medi-connect.
  client/src/components/BusinessContactForm.jsx
  client/src/components/Footer.jsx
  client/src/components/Layout.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level2, hacktoberfest

#422 Fix Login Page Header and User Type Input Field Height Consistency
  client/src/pages/AuthForm.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#419 Feat : Added spinner for registration
  client/src/components/Navbar.jsx
  client/src/components/ReviewDetails.jsx
  client/src/components/StepTwo.jsx
  server/validators/authSchemas.js
Labels: hacktoberfest-accepted, gssoc-extd, gssoc-ext, level2, hacktoberfest

#410 Add OPD Schedule Page
  client/src/components/Layout.jsx
  client/src/components/ReviewDetails.jsx
  client/src/data/databaseUrls.js
  client/src/pages/AuthForm.jsx
  client/src/pages/HospitalDetail.jsx
  client/src/pages/HospitalList.jsx
  client/src/pages/HospitalPanal.jsx
  client/src/pages/OPDRegistration.jsx
  client/src/pages/OPDSchedule.jsx
  client/src/pages/Profile.jsx
  client/src/store/userContext.jsx
  server/controllers/user/profileController.js
  server/models/hospital.js
  server/routes/user/profile.js
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level3, hacktoberfest, gssoc24-ext

#434 changes: chatbot darmode fix and chatbot width bug fix
  client/src/Medical-Chatbot/Chatbot.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-ext, level1, hacktoberfest

#435 back button added : back button added on blogs page and where needed #425 done
  client/src/pages/BlogDetailsPage.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#439 UI Enhanced of AboutUs Section
  client/package-lock.json
  client/src/components/Description.jsx
  client/src/pages/About.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#421 Title: Backend Refactor for Cleaner Code Structure and Better Organization
  server/.prettierrc
  server/README.md
  server/controllers/appointments/appointmentsController.js
  server/controllers/hospital/hospitalController.js
  server/controllers/user/profileController.js
  server/controllers/user/userController.js
  server/docker-compose.yml
  server/index.js
  server/models/user.js
  server/modules/hospital/index.js
  server/modules/user/index.js
  server/routes/appointments/appointment.js
  server/routes/hospital/hospital.js
  server/routes/user/profile.js
  server/seeds/hospitalSeeder.js
  server/utils/notifications/sendMail.js
  server/utils/notifications/sendSMS.js
  server/validators/appointmentSchemas.js
  server/validators/hospitalSchemas.js
  server/validators/userSchemas.js
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#445 Fix Translate Dropdown Persistence in Footer
  client/src/components/Footer.jsx
  client/src/components/GoogleTranslate.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#453 added private routes
  client/package-lock.json
  client/package.json
  client/src/components/Layout.jsx
  client/src/privateroute/privateroute.jsx
  client/src/privateroute/spinner.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#454 added rate limiter to login api issue #440
  server/routes/auth/auth.js
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#457 added validation in booking date
  client/package-lock.json
  client/src/pages/OPDRegistration.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#459 removed second footer
  client/src/components/Layout.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#436 fixed dark mode and alignment #430
  client/src/components/Review.jsx
  client/src/pages/About.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#438 google login implemented
  client/src/components/Navbar.jsx
  client/src/pages/AuthForm.jsx
  client/src/store/userContext.jsx
  server/.env.example
  server/README.md
  server/controllers/auth/authController.js
  server/index.js
  server/middlewares/authMiddleware.js
  server/package.json
Labels: hacktoberfest-accepted, gssoc-ext, level3, hacktoberfest

#471 chore: Added next step validation
  client/src/components/MultiStepRegistration.jsx
  client/src/components/StepTwo.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#465 Forgotpassword : Forgot password feature implemented #283
  client/src/components/ForgotPassword.jsx
  client/src/components/Layout.jsx
  client/src/pages/AuthForm.jsx
  server/controllers/auth/authController.js
  server/models/hospital.js
  server/models/user.js
  server/routes/auth/auth.js
  server/utils/otputils.js
  server/validators/authSchemas.js
Labels: hacktoberfest-accepted, gssoc-ext, level3, hacktoberfest

#475 [Bug Fixed] Fetching location for infinite time after User denied Geo…
  client/src/pages/HospitalsAround.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#498 login page user/hospital selection added : #483 done
  client/src/data/databaseUrls.js
  client/src/pages/AuthForm.jsx
  server/controllers/auth/authController.js
  server/utils/cors/corsConfig.js
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#491 Enhanced the structure and also added some new sections
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#515 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#536 private routes and hospital page added : #468 done
  client/src/components/Navbar.jsx
  client/src/privateroute/privateroute.jsx
  client/src/store/userContext.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#540 Feature#492: Enhance LabTest Cards to include more details. Add redirection for 'Read More'.
  client/src/pages/LabTest.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#518 modified footer open space.
  client/src/components/Footer.jsx
Labels: hacktoberfest-accepted, gssoc, gssoc-extd, gssoc-ext, level1, hacktoberfest

#545 Update README.md added Stargazers and Forkers section to readme.md
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#549 Button and icons hover and animation added
  client/src/components/Navbar.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#551 Added 3d hover effect and animation to cards social media icons
  client/src/pages/About.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#552 Adding Animated Preloader
  client/src/App.js
  client/src/components/PreLoader.jsx
  client/src/styles/Preloader.css
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#557 Fixed: helmet security support
  server/index.js
  server/package.json
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#550 newsletter frontend and backend done : #542 done
  client/package-lock.json
  client/src/components/Footer.jsx
  client/src/components/Layout.jsx
  client/src/pages/Newsletters.jsx
  client/src/store/userContext.jsx
  server/.env.example
  server/controllers/othercontrollers/othercontroller.js
  server/index.js
  server/middlewares/adminMiddleware.js
  server/models/newsletter.js
  server/models/user.js
  server/package.json
  server/routes/otherroutes/otherroutes.js
Labels: hacktoberfest-accepted, gssoc-ext, level3, hacktoberfest

#554 Fixed slider in What Our Community Says section
  client/src/components/Review.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest

#577 Change Background Color on Dark Theme
  client/src/pages/About.jsx
  client/src/pages/HospitalList.jsx
  client/src/pages/Service.jsx
Labels: hacktoberfest-accepted, gssoc-extd, gssoc-ext, level2, hacktoberfest

#576 Match Footer Background with Navbar in Dark Theme
  client/package-lock.json
  client/src/components/Footer.jsx
  client/src/components/Navbar.jsx
  client/src/pages/Profile.jsx
  client/tailwind.config.js
Labels: hacktoberfest-accepted, gssoc-extd, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#570 password show hide icon : Password visible option added on forgot password page.
  client/src/components/ForgotPassword.jsx
Labels: hacktoberfest-accepted, gssoc-ext, level1, hacktoberfest

#569 added steps in the form
  client/package-lock.json
  client/package.json
  client/src/components/Layout.jsx
  client/src/pages/OPDRegistration.jsx
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest, gssoc24-ext

#578 Enhance Registration Form background design
  client/src/components/MultiStepRegistration.jsx
  client/src/styles/Login.css
  client/src/styles/OPD.css
Labels: hacktoberfest-accepted, gssoc-ext, level2, hacktoberfest
